import { routing } from "@/i18n/routing"
import type { Metadata } from "next"
import { Hero } from "./_components/hero"

export const metadata: Metadata = {
  title: "Almira steamatic",
  description: "Generated by create next app",
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Hero />
      {children}
    </div>
  )
}
